services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - api

  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    depends_on:
      - api
