/**
 * CMS publish lifecycle event sent from CMS to backend integration endpoint.
 * Contract-only skeleton; business rules are implemented in API/worker layers.
 */
export interface CmsPublishEvent {
  /** Idempotency key generated by CMS per publish attempt. */
  idempotencyKey: string;
  /** Event type discriminator, e.g. guide.published, patch-note.published. */
  eventType: string;
  /** Entity type that was published. */
  entityType: "guide" | "patch-note" | "meta-snapshot";
  /** Canonical content id in CMS domain. */
  entityId: string;
  /** Publish timestamp (ISO-8601). */
  publishedAt: string;
  /** Firebase UID of the operator/account that triggered publish (if available). */
  actorFirebaseUid?: string;
  /** Version marker for schema evolution. */
  schemaVersion: string;
  /** Opaque payload, to be narrowed by downstream handlers. */
  payload: GuideContentDto | PatchNoteDto | MetaSnapshotDto;
}

/**
 * DTO for guide content synchronized from CMS.
 */
export interface GuideContentDto {
  id: string;
  slug: string;
  title: string;
  summary?: string;
  body: string;
  tags?: string[];
  locale?: string;
  publishedAt?: string;
  updatedAt?: string;
}

/**
 * DTO for patch note content synchronized from CMS.
 */
export interface PatchNoteDto {
  id: string;
  patchVersion: string;
  title: string;
  highlights?: string[];
  body: string;
  publishedAt?: string;
  effectiveAt?: string;
}

/**
 * DTO for meta snapshot content synchronized from CMS.
 */
export interface MetaSnapshotDto {
  id: string;
  snapshotKey: string;
  title: string;
  description?: string;
  dataRef?: string;
  patchVersion?: string;
  publishedAt?: string;
}
